name: ecole_kolea_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1

  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  time_planner: ^0.1.2+1
  date_time: ^0.10.0
  grouped_list: ^5.1.2
  intl: ^0.18.0
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  socket_io_client: ^2.0.0
  path_provider: ^2.1.2
  lottie: ^2.7.0
  top_snackbar_flutter: ^3.1.0
  image_picker: ^1.0.7
  dropdown_button2: ^2.3.9
  get: ^4.1.4
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  workmanager: ^0.5.1
  flutter_local_notifications: ^17.0.0
  flutter_background: ^1.2.0
  permission_handler: ^11.0.1
  flutter_background_service: ^0.1.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  


flutter:


  uses-material-design: true


  assets:
    - lib/Assets/Images/logoHSMDE.png
    - lib/Assets/Images/logo.png
    - lib/Assets/Images/Frame1.png
    - lib/Assets/Images/Frame2.png
    - lib/Assets/Images/Frame3.png
    - lib/Assets/Images/profilpic.jpg
    - lib/Assets/Images/plancours.png
    - lib/Assets/Images/planexams.png
    - lib/Assets/Images/noprofilpic.png
    - lib/Assets/Images/noInternet.png
